### PR TITLE
add plonk verifier: support single proof verification

### PR DESCRIPTION
**Pull request by lightning-li**

### CODE REVIEW

**Comment by lightning-li** [comment]
I write an example of how to use `PlonkVerifier.sol`, see https://github.com/lightning-li/plonk_verifier_example for details.

**Comment by gbotrel** [comment]
Thanks for this contribution, very useful indeed 👍  .

**Comment by gbotrel** [comment]
hey -- just a quick note, we have couple of events next week and won't have time to look at that until the following one at least.

**Comment by gbotrel** [comment]
@lightning-li do you have an example code of conversion from the `gnark` Proof data structure:
```
type Proof struct {

	// Commitments to the solution vectors
	LRO [3]kzg.Digest

	// Commitment to Z, the permutation polynomial
	Z kzg.Digest

	// Commitments to h1, h2, h3 such that h = h1 + Xh2 + X**2h3 is the quotient polynomial
	H [3]kzg.Digest

	// Batch opening proof of h1 + zeta*h2 + zeta**2h3, linearizedPolynomial, l, r, o, s1, s2
	BatchedProof kzg.BatchOpeningProof

	// Opening proof of Z at zeta*mu
	ZShiftedOpening kzg.OpeningProof
}
```

To the one you added in the solidity template:

```
    struct Proof {
        uint256[] input_values;
        PairingsBn254.G1Point[STATE_WIDTH] wire_commitments;  // [a(x)]/[b(x)]/[c(x)]
        PairingsBn254.G1Point grand_product_commitment;      // [z(x)]
        PairingsBn254.G1Point[STATE_WIDTH] quotient_poly_commitments;  // [t_lo]/[t_mid]/[t_hi]
        PairingsBn254.Fr[STATE_WIDTH] wire_values_at_zeta;   // a(zeta)/b(zeta)/c(zeta)
        PairingsBn254.Fr grand_product_at_zeta_omega;        // z(w*zeta)
        PairingsBn254.Fr quotient_polynomial_at_zeta;        // t(zeta)
        PairingsBn254.Fr linearization_polynomial_at_zeta;   // r(zeta)
        PairingsBn254.Fr[STATE_WIDTH-1] permutation_polynomials_at_zeta;  // Sσ1(zeta),Sσ2(zeta)

        PairingsBn254.G1Point opening_at_zeta_proof;            // [Wzeta]
        PairingsBn254.G1Point opening_at_zeta_omega_proof;      // [Wzeta*omega]
    }
```

?

**Comment by lightning-li** [comment]
> 

Yes, see the conversion code here: https://github.com/lightning-li/plonk_verifier_example/blob/main/proof_generation/src/main.go#L57

**Comment by lightning-li** [comment]
> @lightning-li do you have an example code of conversion from the `gnark` Proof data structure:
> 
> ```
> type Proof struct {
> 
> 	// Commitments to the solution vectors
> 	LRO [3]kzg.Digest
> 
> 	// Commitment to Z, the permutation polynomial
> 	Z kzg.Digest
> 
> 	// Commitments to h1, h2, h3 such that h = h1 + Xh2 + X**2h3 is the quotient polynomial
> 	H [3]kzg.Digest
> 
> 	// Batch opening proof of h1 + zeta*h2 + zeta**2h3, linearizedPolynomial, l, r, o, s1, s2
> 	BatchedProof kzg.BatchOpeningProof
> 
> 	// Opening proof of Z at zeta*mu
> 	ZShiftedOpening kzg.OpeningProof
> }
> ```
> 
> To the one you added in the solidity template:
> 
> ```
>     struct Proof {
>         uint256[] input_values;
>         PairingsBn254.G1Point[STATE_WIDTH] wire_commitments;  // [a(x)]/[b(x)]/[c(x)]
>         PairingsBn254.G1Point grand_product_commitment;      // [z(x)]
>         PairingsBn254.G1Point[STATE_WIDTH] quotient_poly_commitments;  // [t_lo]/[t_mid]/[t_hi]
>         PairingsBn254.Fr[STATE_WIDTH] wire_values_at_zeta;   // a(zeta)/b(zeta)/c(zeta)
>         PairingsBn254.Fr grand_product_at_zeta_omega;        // z(w*zeta)
>         PairingsBn254.Fr quotient_polynomial_at_zeta;        // t(zeta)
>         PairingsBn254.Fr linearization_polynomial_at_zeta;   // r(zeta)
>         PairingsBn254.Fr[STATE_WIDTH-1] permutation_polynomials_at_zeta;  // Sσ1(zeta),Sσ2(zeta)
> 
>         PairingsBn254.G1Point opening_at_zeta_proof;            // [Wzeta]
>         PairingsBn254.G1Point opening_at_zeta_omega_proof;      // [Wzeta*omega]
>     }
> ```
> 
> ?

Yes, see the conversion code here: https://github.com/lightning-li/plonk_verifier_example/blob/main/proof_generation/src/main.go#L57 . I can't directly access `Proof` struct of package `internal/backend/bn254`, so I have to marshal proof first and split marshal bytes into `Proof` fields, then convert it to solidity `Proof` struct. Maybe it's not a good solution, but for now it works!

**Comment by gbotrel** [comment]
Awesome thanks; derived this into our integration test https://github.com/ConsenSys/gnark-tests/blob/5b75ba1ccadf836ce9256780f0e26c98e38c5f43/solidity/solidity_plonk_test.go#L158 . 


Note that I had to modify a line in the solidity template (maybe due to changes in recent solc compile output) (see #366 ).

**Pull request merged**
