### PR TITLE
Feat/plonk verifier batching

### PR DESCRIPTION
**Pull request by ThomasPiellard**
# Description

Adds a base circuit for batching plonk verifier circuits in a 2 chain.

Might conflict with #949 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [x] TestBatchVerify

# How has this been benchmarked?

`~295k` constraints per verifier

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ivokub** [comment]
I think we need to sync with @AlexandreBelling to understand how the aggregation circuit should look. I had assumed that we also switch on the circuit type. Currently we hardcode all the circuits we want to verify.

**Comment by ivokub** [comment]
Converted this PR to draft until have confirmation.

**Comment by AlexandreBelling** [comment]
I am fine if the verification keys are assumed to be constants

**Comment by ivokub** [comment]
Done, see the tests `TestBLS12InBW6Multi` and `TestBLS12InBW6MultiHashed` for the usage.

Approx 287k constraints per circuit on average (over 20 circuits). If using hashing to save number of public inputs, then approx 288k constraints per circuit.

**Review by ivokub — APPROVED** [review]
Good for me. But I guess I have made significant changes so would be good for @ThomasPiellard to also look before merging.

**Pull request merged**
