### PR TITLE
Optimized BN254 Groth16 Solidity template with compressed proof support

### PR DESCRIPTION
**Pull request by recmo**
New verifier BN254 Groth16 Solidity template that is more gas efficient and supports compressed proofs (efficient on rollups).

External audit scheduled for this week.

It has two public functions `verifyProof` and `verifyCompressedProof`.

The `verifyProof` is heavily gas optimized and should be drop-in replacement for the existing function (except it will always revert on invalid proof, instead of sometimes returning false).

The `verifyCompressedProof` is optimized for reducing calldata, and less optimized for compute. This is to keep readability in the much more complex math. The intended use case is rollups where calldata is relatively much more expensive than compute.

### CODE REVIEW

**Comment by gbotrel** [comment]
> External audit scheduled for this week.
hi @recmo --> when is the report due?

**Comment by recmo** [comment]
Received the first iteration yesterday and am now implementing the three suggestions (there where no issues):

* Suggestion 1: Use Custom Error Messages  
* Suggestion 2: Collaborate With Gnark To Implement the Compress Function
* Suggestion 3: Adhere to Natspec Guidelines

I've asked if I can share the report.

**Comment by recmo** [comment]
Final audit report:

[Least Authority- Worldcoin Groth16 Verifier in EVM Smart Contract Final Audit Report.pdf](https://github.com/Consensys/gnark/files/12442249/Least.Authority-.Worldcoin.Groth16.Verifier.in.EVM.Smart.Contract.Final.Audit.Report.pdf)

**Comment by recmo** [comment]
@gbotrel From my side this is ready to merge. LMK what next steps are.

**Comment by kustosz** [comment]
@gbotrel I also have a wip branch on `gnark-tests` to run against this version (https://github.com/kustosz/gnark-tests/tree/evm-verifier), though I had to make some other changes due to version mismatch between `gnark` master and whatever `gnark-test` is building against. Please let me know how and when to best PR the test changes.

**Comment by gbotrel** [comment]
@kustosz so, we are now running solidity integration test within gnark main repo CI;

https://github.com/Consensys/gnark/blob/0896fe1cfcac6bfad9e2621580a653132516ba8b/test/assert_solidity.go#L21

so if you can add the test for the compress proof in there and it passes the CI looks good to merge on our side.

Q: @Tabaie @ThomasPiellard  I suspect plugging the multi commit on top of that shouldn't be an issue?

**Comment by kustosz** [comment]
Thanks for the pointer, will get this sorted tomorrow!

**Comment by kustosz** [comment]
@gbotrel [here's](https://github.com/Consensys/gnark-solidity-checker/pull/1) a PR to the solidity checker that makes the tests here pass locally – can you please verify against your CI?

**Comment by kustosz** [comment]
just to be clear: the CI here won't pass until https://github.com/Consensys/gnark-solidity-checker/pull/1 gets merged (or at least put on a branch in that repo so we can refer to it in CI config here)

**Pull request merged**
