### PR TITLE
Perf: KZG verify gadget

### PR DESCRIPTION
**Pull request by yelhousni**
# Description

**(Refactored as in #930 )**

The current KZG verify gadget computes (in `AssertProof`) the multi-pairing `e(totalG1, vk.SRS[0]) * e(negQuotientPoly, vk.SRS[1]) == 1` assuming all arguments are variable. However `vk.SRS[0]=G₂` and `vk.SRS[1]=[α]G₂` are fixed points in G2. This PR pre-computes the lines used in the multi-pairing hence avoiding G2 arithmetic in-circuit.

TODO: 
- [x] pre-compute lines from `vk.SRS[0]=G₂`
- [x] pre-compute lines from `vk.SRS[1]=[α]G₂`
- [x] implement `DoublePairingFixedQCheck` which does `e(var, fix) * e(var, var) == 1`
  - [x] BN254
  - [x] BLS12-381
  - [x] BW6-761 ~(Naive algorithm for now)~
  - [x] BLS12-377
  - [x] BLS24-315
- [x] implement `DoublePairingFixedQCheck` which does `e(var, fix) * e(var, fix) == 1`
- [x] make the fixed pairing agnostic/generic wrt fixed argument + lazy pre-computation
- [x] use new function in KZG verify gadget

N.B.: To do the same for BW6-761, we need to revisit the Miller loop algortihm to be an ate loop instead of a Tate. Will do in a separate PR.
*Edit: This was done in https://github.com/Consensys/gnark/pull/876 and merged here*

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

Same existing tests work for the new feature.

# How has this been benchmarked?

- *Emulated case:* verifying a KZG proof on BW6-761 with a BN254-SNARK:

|     | Old  | New |
|---|---|---|
|R1CS | 5,171,863 | 4,147,830 |
|SCS   | 49,547,799 | 38,776,383 |

This is a 10.7M+ saving in SCS which largely offsets the 24k loss in https://github.com/Consensys/gnark/pull/876/ due to Miller algorithm change.

-  *Native case:* verifying a KZG proof on BLS12-377 with a BW6-761-SNARK:

|     | Old  | New |
|---|---|---|
|R1CS | 18,390 | 16,414 |
|SCS   | 74,128 | 68,502 |

This is a 5.6k saving in SCS. A pairing in native already does not cost much.

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by yelhousni** [comment]
@ivokub @ThomasPiellard this PR is ready for review. It needs first https://github.com/Consensys/gnark-crypto/pull/466 to be merged. I merged master here and resolved conflicts with your previous work and all seem to work nicely.

**Comment by yelhousni** [comment]
@ivokub this PR is good to go on my end. Your call if you want to merge as-is or contribute your refactoring here.

**Comment by ivokub** [comment]
> @ivokub this PR is good to go on my end. Your call if you want to merge as-is or contribute your refactoring here.

Great work! I think I'll refactor and wait until the plonk verifier PR is done. I'm afraid there would be otherwise merge conflicts.

**Comment by yelhousni** [comment]
@ivokub @ThomasPiellard I refactored this PR to follow the same pattern as in #930 for all curves. PR is ready for review.

**Pull request merged**
