### PR TITLE
Faster cubic 01 01 mul

### PR DESCRIPTION
**Pull request by shramee**
# Description

Faster `Mul01By01` for cubic extensions.
Saves:
  - 2 muls
  - 4 sub/add
  - 1 mul by non residue

## Type of change

- [x] New feature (non-breaking change which adds functionality) - Optimisation

# How has this been tested?

- [x] [faster Mul01By01](https://github.com/Consensys/gnark/commit/2845b9bc73893b62b0a5f0b289c3bef29d272100)
- [x] [bn254: test mul 01 by 01](https://github.com/Consensys/gnark/commit/718671d7eaff8dd9d48542b76b3cb7cfafd291f3)
- [x] [bls12377: test mul 01 by 01](https://github.com/Consensys/gnark/commit/10215c62091b2bd2e67730e59f2c4aef547dadf8)

# How has this been benchmarked?

This was not benched but it,
1. For E6 Mul01By01 reduces,
  - 2 E2 muls
  - 4 E2 sub/add
  - 1 mul by non residue
2. For E3 Mul01By01 reduces,
  - 2 muls
  - 4 sub/add
  - 1 mul by non residue

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by shramee** [comment]
Details about the updates here,

https://github.com/shramee/cairo_bn/commit/fa51da864c63f9de4345903f108dbd184875ff55#diff-2c7236b88c6be3cac67ffcbd5e19ee3fb1a72ce9f8bd1089506a736dbd6d23c6L110

**Comment by yelhousni** [comment]
lol that must have been a silly copy-paste I did ^^ Thank you for the catch!

**Comment by yelhousni** [comment]
@shramee that looks good, thanks for your contribution to gnark!
You just need to update the circuits stats to pass the CI tests:

1. Change `false` to `true` here https://github.com/Consensys/gnark/blob/1ed22f78eac88c89d10d3be5a7741f6d5cb0ca29/internal/stats/generate/main.go#L15
2. Run `go run main.go` in `internal/stats/generate`
3. Commit the modified `latest.stats` file in `internal/stats`
4. Change back `true` to `false`

Also you would need to sign the Contributor License Agreement. Thanks again!

**Comment by shramee** [comment]
Done!
Where can I sign the Contributor License Agreement?

**Review by yelhousni — APPROVED** [review]

**Pull request merged**
