### PR TITLE
Fix: Bandersnatch GLV scalar multiplication

### LINKED ISSUE #268: Hinted scalar decomposition in a gadget
In SW and tEd gadgets, when using the hinted scalar decomposition for GLV, we only check that `s1 + λ * s2 == s + k*o` but this is done `mod r` (where `o` is the order of SW/tEd curve prime subgroup and `r` the order of the SNARK curve prime subgroup).

It means that in Z: `s1 + λ * s2 - s - k*o = c * r` but with no guarantee that `c` is always `0`.  We should look for edge cases if any and constrain them or look for a better constrained decomposition.

### PR DESCRIPTION
**Pull request by yelhousni**
# Description

Fixes #268

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

`TestCurve` for Bandersnatch pass when using `scalarMulGLV`.

# How has this been benchmarked?

`Bandersnatch` in R1CS:
2-bit windowed double-and-add: **3,314**
GLV: **2,735** 
`Bandersnatch` in SCS:
2-bit windowed double-and-add: **5,991**
GLV: **6,077** 

So the GLV saves 579 r1cs but adds 86 scs, which is because of the non-native scalar decomposition check. In this PR we use GLV only if endomorphism + R1CS.

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by gbotrel — APPROVED** [review]
A remark, that probably applies to other neighbor pacakges;

I checked the call graph to see how it is tested, and it seems we just test with `testData` --> with random scalars. 

Should we add some edge cases tests ? (i.e. scalar at 0, p-1, 1, ...),

**Review by ivokub — APPROVED** [review]
Looks perfect! I only added some comments what my local linter mentioned (unused arguments in methods).

**Review by ivokub — APPROVED** [review]
Looks good again. Maybe we should add a comment to the `Curve` interface that the methods ScalarMul, Add etc. do not check that point is on the curve.

For the future, it would be nice to also implement this - https://github.com/Consensys/gnark/issues/1159. There was actually a discussion related to it just recently - https://github.com/Consensys/gnark/discussions/1292

**Comment by yelhousni** [comment]
Closing since superseded by the fake GLV

**Pull request closed without merging**
