### PR TITLE
feat: expmod with variable modulus

### LINKED ISSUE #573: feat: add Modexp precompile
Before closing issue ensure we have a constraint count + a matching test with the exact interface.

### PR DESCRIPTION
**Pull request by ivokub**
# Description

This PR implements subset of non-native arithmetic which allows to use non-default modulus for multiplication and subtraction. This is achieved by using non-default modulus in the multiplication checks and reimplementing subtraction padding computation to use non-constant modulus to avoid underflows. Using the implementations, we additionally implement variable-input expmod.

Necessary for implementing expmod precompile.

For witness allocation, we have to still define some upper limit on the modulus which in this case will be 4096 bits i.e. any 64 limb element.

Closes #573 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

- [x] Variable modulus addition
- [x] Variable modulus multiplication
- [x] Variable modulus subtraction
- [x] Variable modulus equality assertion

# How has this been benchmarked?

- PLONK variable modulus expmod with 512-bit elements: 967_995
- R1CS variable modulus expmod with 512-bit elements: 246_777
- PLONK variable modulus expmod with 4k-bit elements: 44_214_331
- R1CS variable modulus expmod with 4k-bit elements: 11_675_777
- PLONK fixed modulus expmod with 512-bit elements: 673_554
- R1CS fixed modulus expmod with 512-bit elements: 172_645
- PLONK fixed modulus expmod with 4k-bit elements: 30_052_625
- R1CS fixed modulus expmod with 4k-bit elements: 7_997_133

The approx 50% performance penalty comes due to that we're not able to estimate the length of the quotient `k` in the multiplication check `a*b = r + k*p`, as when actual value of `p` decreases then `k` increases. For fixed-modulus, we know exactly the length of `p` and can bound the length for `k`. As `k` comes from the hint, then this requires more range checking.

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ivokub** [comment]
cc @yelhousni. FYI the implementation for variable-mod expmod. Maybe there is an approach which uses NAF-decomposition instead of binary for reducing the number of loops in square-and-mul.

**Comment by yelhousni** [comment]
> cc @yelhousni. FYI the implementation for variable-mod expmod. Maybe there is an approach which uses NAF-decomposition instead of binary for reducing the number of loops in square-and-mul.

@ivokub I couldn't make the 2-NAF approach work with less constraints that the current approach. It's mainly because we need a size-3 Mux and do a multiplication per iteration anyway regardless of the bits representation.

However, this simple edit saves 10k scs:
```diff
diff --git a/std/math/emulated/custommod.go b/std/math/emulated/custommod.go
index 2c982228..2f5cbaca 100644
--- a/std/math/emulated/custommod.go
+++ b/std/math/emulated/custommod.go
@@ -87,10 +87,13 @@ func (f *Field[T]) ModAssertIsEqual(a, b *Element[T], modulus *Element[T]) {
 // NB! circuit complexity depends on T rather on the actual length of the modulus.
 func (f *Field[T]) ModExp(base, exp, modulus *Element[T]) *Element[T] {
        expBts := f.ToBits(exp)
-       res := f.One()
-       for i := range expBts {
+       n := len(expBts)
+       res := f.Select(expBts[0], base, f.One())
+       base = f.ModMul(base, base, modulus)
+       for i := 1; i < n-1; i++ {
                res = f.Select(expBts[i], f.ModMul(base, res, modulus), res)
                base = f.ModMul(base, base, modulus)
        }
+       res = f.Select(expBts[n-1], f.ModMul(base, res, modulus), res)
        return res
 }
```

**Comment by ivokub** [comment]
> > cc @yelhousni. FYI the implementation for variable-mod expmod. Maybe there is an approach which uses NAF-decomposition instead of binary for reducing the number of loops in square-and-mul.
> 
> @ivokub I couldn't make the 2-NAF approach work with less constraints that the current approach. It's mainly because we need a size-3 Mux and do a multiplication per iteration anyway regardless of the bits representation.
> 
> However, this simple edit saves 10k scs:
> 
> ```diff
> diff --git a/std/math/emulated/custommod.go b/std/math/emulated/custommod.go
> index 2c982228..2f5cbaca 100644
> --- a/std/math/emulated/custommod.go
> +++ b/std/math/emulated/custommod.go
> @@ -87,10 +87,13 @@ func (f *Field[T]) ModAssertIsEqual(a, b *Element[T], modulus *Element[T]) {
>  // NB! circuit complexity depends on T rather on the actual length of the modulus.
>  func (f *Field[T]) ModExp(base, exp, modulus *Element[T]) *Element[T] {
>         expBts := f.ToBits(exp)
> -       res := f.One()
> -       for i := range expBts {
> +       n := len(expBts)
> +       res := f.Select(expBts[0], base, f.One())
> +       base = f.ModMul(base, base, modulus)
> +       for i := 1; i < n-1; i++ {
>                 res = f.Select(expBts[i], f.ModMul(base, res, modulus), res)
>                 base = f.ModMul(base, base, modulus)
>         }
> +       res = f.Select(expBts[n-1], f.ModMul(base, res, modulus), res)
>         return res
>  }
> ```

Good catch! Indeed this helps. I also implemented for the fixed-modulus case.

**Review by yelhousni — APPROVED** [review]
LGTM 👍

**Pull request merged**
