### PR TITLE
Nix build

### PR DESCRIPTION
**Pull request by morganthomas**

### CODE REVIEW

**Comment by gbotrel** [comment]
@morganthomas hi! I suspect target for this PR was your fork? :-)

**Comment by morganthomas** [comment]
Hi @gbotrel ! This PR is pointed at its intended target but it's just a draft. There are some issues with these changes: some hacks I did to make the tests pass in the Nix build. I am wondering if the project is in principle interested in having Nix build code upstreamed, and if so then I could look at making these changes upstreamable by reducing the hacks.

**Comment by gbotrel** [comment]
not familiar with Nix; why would we want a Nix build?

**Comment by morganthomas** [comment]
Hi, @gbotrel . The benefit Nix offers is reproducible builds, so that without any hassle, one can download some source code and produce a build which is for all intents and purposes the same as the one the developers built from the same source.

**Pull request closed without merging**
