### PR TITLE
feat: add gadget for enabling multiple commitments in-circuit

### PR DESCRIPTION
**Pull request by ivokub**
In the end I took the callback approach. It seemed the most cleanest. I understand that the callback-based approach is too bit JavaScript-y, but it was quite straightforward to implement and I'm quite confident it is correct.

@Tabaie - how does this look to you particularly?

### CODE REVIEW

**Comment by ivokub** [comment]
Just a comment how this works. Previously we computed the commitment as
```
C = Commit(x1, x2, .., xn)
```
where variables `x1, ..., xn` were commited to and the commitment is `C`. When trying to compute multiple commitments we get a panic
```
C = Commit(x1, x2, ..., xn)
C2 = Commit(y1, y2, ..., yn) // panic, we can only compute a single commitment per circuit
```

With this PR, we propose a framework to collect all variables to commit and the functions where the commitments will be used. Essentially, we do
```
root = Commit(x1, x2, ..., xn, y1, y2, ..., yn)
C1 = Hash(1, root)
C2 = Hash(2, root)
// now can use C1 and C2 as independent commitment in-circuit
```

For the hash function we use MiMC hash. The scheme is binding because due to preimage resistance of MiMC, we are prevented from computing suitable `root`. The commitments are independent because MiMC is collision resistant.

**Review by Tabaie — APPROVED** [review]
LGTM! However I do think in the long run there's no escaping the need to enable multiple `api.Commit` calls. The only way I can imagine it now would involve more and even dirtier hint hacks than we have now.

**Comment by ivokub** [comment]
> LGTM! However I do think in the long run there's no escaping the need to enable multiple `api.Commit` calls. The only way I can imagine it now would involve more and even dirtier hint hacks than we have now.

Great, thanks! I'll wait with merging for a bit, I think @gbotrel also had ideas about the interface. Don't want to have something unidiomatic sticking around for ages.

**Comment by gbotrel** [comment]
mmhh overall I like that it's a simple PR; but, the name "native" confused me at first. Also, when we have introduce the risk to have something like 

```go 
c.X = api.Add(...)
native.WithCommitment(api, func(api frontend.API, commitment frontend.Variable) error {
 		// compute (X-s[0]) * (X-s[1]) for a random X
 		c.X = api.Mul(c.X, api.Sub(commitment, c.Secrets[1]))
 		api.AssertIsDifferent(c.X, 0)
 		return nil
 	}, c.Secrets[:2]...)
 Y = api.Mul(c.X, ...)
```

(ie we put forward an "async" programming model while the rest of the API is not)

**Comment by gbotrel** [comment]
```go
// we can share variables between the callbacks
	var shared, stored frontend.Variable
	native.WithCommitment(api, func(api frontend.API, commitment frontend.Variable) error { // cb4
		shared = api.Add(c.Secrets[0], commitment)
		stored = commitment
		return nil
	})
	native.WithCommitment(api, func(api frontend.API, commitment frontend.Variable) error { // cb5
		api.AssertIsEqual(api.Sub(shared, stored), c.Secrets[0])
		return nil
	})
```

huh

**Comment by gbotrel** [comment]
question; since the `api.Commit` value is the result of a hint. couldn't we make that hint stateful and handle the logic in the consecutive calls to the hint? (which is injected in a single solving instance of the constraint system anyway?)

**Comment by gbotrel** [comment]
@Tabaie I'm probably missing a step but technically;
```
v1 := api.Commit(s1, s2)
v2 := api.Commit(s3,s4)
``` 
how are v1 and v2 computed behind the scenes so we have a single commitment in the proving key ?

**Comment by Tabaie** [comment]
In this PR we don't actually make multiple calls to `api.Commit`. The gadget registers callbacks and aggregates all committed values into a single call to `api.Commit`.
Was that your question or did I misunderstand?

**Comment by gbotrel** [comment]
yeah my question is; what if we don't do this PR with async callbacks, and do multiple api.Commit; what does it take behind the scene? Can't the same "defer" logic be handled at the hint level by being "stateful" and maintaining a single commitment in the proving key? 

to put it bluntly, I don't understand why it's complicated to modify the hint that handles api.Commit to do multi commit, because I don't understand what it is "morally" supposed to do if we were to have multiple api.Commit calls

**Comment by ivokub** [comment]
> ```go
> // we can share variables between the callbacks
> 	var shared, stored frontend.Variable
> 	native.WithCommitment(api, func(api frontend.API, commitment frontend.Variable) error { // cb4
> 		shared = api.Add(c.Secrets[0], commitment)
> 		stored = commitment
> 		return nil
> 	})
> 	native.WithCommitment(api, func(api frontend.API, commitment frontend.Variable) error { // cb5
> 		api.AssertIsEqual(api.Sub(shared, stored), c.Secrets[0])
> 		return nil
> 	})
> ```
> 
> huh

Essentially I wanted to show that it is possible to share variables between the callbacks, if done carefully (understanding that the callbacks are executed FIFO order). But not that I recommend doing it.

**Comment by ivokub** [comment]
> mmhh overall I like that it's a simple PR; but, the name "native" confused me at first. Also, when we have introduce the risk to have something like
> 
> ```go
> c.X = api.Add(...)
> native.WithCommitment(api, func(api frontend.API, commitment frontend.Variable) error {
>  		// compute (X-s[0]) * (X-s[1]) for a random X
>  		c.X = api.Mul(c.X, api.Sub(commitment, c.Secrets[1]))
>  		api.AssertIsDifferent(c.X, 0)
>  		return nil
>  	}, c.Secrets[:2]...)
>  Y = api.Mul(c.X, ...)
> ```
> 
> (ie we put forward an "async" programming model while the rest of the API is not)

Agree, `native` is not good name for the package. But when trying to fit it in `std/commitment`, then seemed suitable. But actually I think something like `std/randomoracle` is even more suitable, because this is imo actually what this package provides.

**Comment by ivokub** [comment]
> yeah my question is; what if we don't do this PR with async callbacks, and do multiple api.Commit; what does it take behind the scene? Can't the same "defer" logic be handled at the hint level by being "stateful" and maintaining a single commitment in the proving key?
> 
> to put it bluntly, I don't understand why it's complicated to modify the hint that handles api.Commit to do multi commit, because I don't understand what it is "morally" supposed to do if we were to have multiple api.Commit calls

Technically, it can be done but imo it has several consequences (see also discussion in #394):
* we need to have separate commitment key for every call to `Commit`. And the verifier needs to verify every commitment separately. So the verification wouldn't be three pairings anymore, but 3+nbCommitments.
* I'm also afraid it will cause soundness problems. Essentially the commitment is a Pedersen hash of the inputs for a basis which depends on the proving key. An adversary would be able to predict the value of second commitment from the first commitment if the inputs to the commitments are similar. See for example grjte writeup which imo captures the problem well: https://hackmd.io/@grjte/zk-hack-5-strong-adaptivity. Now, if we do it like in this PR (only one Pedersen hash as a commitment and then MiMC for separation), then we do not have the issue as all commitments are independent from each other (thanks to collision-resistance of MiMC).

**Comment by gbotrel** [comment]
mmhh got you and couldn't we do a non-async programming model ? ie have 
```
v1 := api.Commit(s1, s2)
v2 := api.Commit(s3,s4)
```
and let the frontend package do the MiMC for separation between calls or something?

**Comment by ivokub** [comment]
> mmhh got you and couldn't we do a non-async programming model ? ie have
> 
> ```
> v1 := api.Commit(s1, s2)
> v2 := api.Commit(s3,s4)
> ```
> 
> and let the frontend package do the MiMC for separation between calls or something?

I think theoretically we can, but I think implementation-wise it would be a bit fragile. What I'm thinking, is that we can do something like this:
```go
var collected []frontend.Variable
var retvars []frontend.Variable

func (builder *r1cs) AsyncCommit(vars ...frontend.Variable) {
    collected = append(collected, vars...)
    retvar := builder.newInternalVariable()
    return retvar
}

func (builder *r1cs) RunAsyncedCommitments() {
    rootcommitment := builder.Commit(collected...)
    for i := range retvars {
        ctxcommit := mimc.Sum(i+1, rootcommitment)
        builder.addConstraint(1 * retvars[i] = ctxcommit)
    }
}

func (c *Circuit) Define(api frontend.API) error {
    v1 := api.AsyncCommit(s1, s2)
    v2 := api.AsyncCommit(s3,s4)
    // do stuff with v1 v2 here
    return nil
    // now we run deferred api.RunAsyncedCommitments() to generate the constraints.
    // the solver then first computes the commitment, ctxcommitments and then solve everything which depends on v1 and v2
}
```

But it isn't that easy - in `AsyncCommit` we also have to check that we do not have any recursive cycles (we asynccommit to something which is a linear combination of a commitment). Maybe if it is obvious?

Second thing is that we have to embed multi-commitment in the builders. Which isn't a big problem actually.


(now looking at the example it seems that the second approach is actually a lot better if we can get it right)

**Comment by gbotrel** [comment]
ok you both convinced me that this is a necessary evil (and simple solution), that hopefully won't get too invasive 👍

**Comment by gbotrel** [comment]
(I like syntax of second example better I think, but I'll let you judge here -- if doing first version unblocks things let's go w ith that, mark it experimental and re-iterate later down the road)

**Comment by Tabaie** [comment]
@ivokub I'm a bit torn between requiring an `api` input to the callback or not. If we're mostly expecting lambdas here they can just use the `api` variable already available. I'm not sure though (that the callback would always be lambdas.)

**Comment by ivokub** [comment]
> @ivokub I'm a bit torn between requiring an `api` argument to the callback or not. If we're mostly expecting lambdas here they can just use the `api` variable already available and have a simpler interface. I'm not sure though (that the callback would always be lambdas.)

Hmm, I think theoretically we can without api in callbacks, but the passed implementations may actually be different. For example we could pass non-commiting version of the builder to the callback (as committing in the callback is illegal anyway). This ensures that we cannot type assert api to `frontend.Committer`.

But I'm not directly opposed to it. I'll try to figure out if the non-async version doesn't work out.

**Comment by ivokub** [comment]
@gbotrel, ping.

I tried out the synchronous approach in [1ca9426](https://github.com/ConsenSys/gnark/pull/562/commits/1ca94267937270af1018f078383326c2f3156ce2). It seems to work (at least the test doesn't fail). Maybe you can have a quick look if this makes sense? If so, then I will try out in bigger circuits and will polish into a nice PR.

There is still some work to do:
* dunno if wire levels should use slice of ints instead of map. It was just easier to work it that way.
* there is one suboptimal loop in `AssignToLazyVariable`. We could track the value instead of big loop.
* Implement for PLONK
* Think about the commitment separation (right now in PR use squaring, but maybe need hashing. Or maybe have something parametric?)
* maybe something else...

I'm not 100% confident though that is is correct :/

**Comment by ivokub** [comment]
Removed the sync variant from the PR. It seems to work but waiting for other optimisations which handle the wire solving dependency graph.

Also moved the package to internal to prevent using externally.

**Pull request merged**
