### PR TITLE
Refactor(BW6-761): use revisited Ate pairing instead of Tate

### PR DESCRIPTION
**Pull request by yelhousni**
# Description

Revisit the Miller loop algorithm from https://github.com/Consensys/gnark/pull/846 to allow fixed-argument pairings needed for KZG optimization (see https://github.com/Consensys/gnark/pull/874). TL;DR: use Eq. (6') instead of (6) in https://hackmd.io/@gnark/BW6-761-changes.

The PR needs gnark-crypto PR https://github.com/Consensys/gnark-crypto/pull/465 for testing.

TODO:
- [x] Implement revisited ate Miller loop
- [x] Implement fixed-argument revisited ate Miller loop

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How has this been tested?

Same existing tests work fine + new tests for fixed-argument pairing (compare pairing result to gnark-crypto).

# How has this been benchmarked?

|     | Old  | New |
|---|---|---|
|R1CS | 2,764,966 | 2,762,882 |
|SCS | 28,191,311 | 28,215,838 |

We lost 2084 R1CS and 24527 SRS for a single pairing compared to `master` but this should be offset in KZG gadget #874 with the fixed-argument pairing that the new Miller loop allows (see below).

|     | Fixed-argument pairing  |
|---|---|
|R1CS | 2,133,509 |
|SCS | 22,481,220 |

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ivokub — APPROVED** [review]
LGTM

**Review by ivokub — CHANGES_REQUESTED** [review]
Actually, I was relooking and there were some errors. Will submit another review after testing and recompiling

**Comment by yelhousni** [comment]
> Actually, I was relooking and there were some errors. Will submit another review after testing and recompiling

There was an old test of a function that does not exist anymore (`MulBy034`) — replaced it by the new test of `MulBy014`.

**Comment by yelhousni** [comment]
> Actually, I was relooking and there were some errors. Will submit another review after testing and recompiling

There was an old test of a function that does not exist anymore (`MulBy034`) — replaced it by the new test of `MulBy014`.

**Review by ivokub — APPROVED** [review]
Yup, running the KZG and Groth16 examples also timeouted my other PR. And the test with Mul034 was the failing one. Now looks perfect!

**Pull request merged**
