### PR TITLE
fix: assign baseChallenge correctly while verifying gkr solution

### PR DESCRIPTION
**Pull request by ahmetyalp**
# Description

Fixes failed assertion while verifying GKR solution(`(gkr.Solution).Verify` function) with other than non-constant hash functions (like mimc or poseidon). Inspired by https://github.com/Consensys/gnark-crypto/blob/master/ecc/bn254/fr/gkr/gkr.go#L688

I added new test case `TestMiMCFullDepthNoDepSolveWithMiMCHash`, which fails without this change with following error:
```
Error:      	Received unexpected error:
        	            	constraint #37111 is not satisfied: [assertIsEqual] 10420734889032269308690831442195287995987323506521353207282897974178519295845 == 19485199868485599785212267512534296132678646505698908814492864400056160446973
        	            	r1cs.(*builder).AssertIsEqual
        	            		/Users/ahmety/gnark/frontend/cs/r1cs/api_assertions.go:38
        	            	gkr.(*eqTimesGateEvalSumcheckLazyClaims).VerifyFinalEval
        	            		/Users/ahmety/gnark/std/gkr/gkr.go:110
        	            	sumcheck.Verify
        	            		/Users/ahmety/gnark/std/sumcheck/sumcheck.go:104
        	            	gkr.Verify
        	            		/Users/ahmety/gnark/std/gkr/gkr.go:339
        	            	gkr.Solution.Verify
        	            		/Users/ahmety/gnark/std/gkr/compile.go:197
        	            	gkr.(*mimcNoDepCircuit).Define
        	            		/Users/ahmety/gnark/std/gkr/api_test.go:596

        	Test:       	TestMiMCFullDepthNoDepSolveWithMiMCHash
```

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Any GKR solution verification with non-constant hash function is failing at same step(`VerifyFinalEval`). `TestMiMCFullDepthNoDepSolveWithMiMCHash` added to reproduce the error

# How has this been benchmarked?

Not benchmarked

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ivokub — APPROVED** [review]
Looks perfect! Thanks for reporting the issue and proposing a fix.

**Comment by ahmetyalp** [comment]
@ivokub Thanks for a quick review. Is there any chance to backport this fix to version 0.9.1?

**Comment by ivokub** [comment]
Hmm, I'll see what we can do - I think we can soon release v0.9.2 or v0.10.0 from master as we try to keep it stable and have a few new features what would be nice to have released. Would this (i.e. new release from master instead of backporting to v0.9.1) work or are there any incompatibilities? For example, if in your project you would `go get github.com/consensys/gnark@master` then should be using latest stable rolling release.

**Comment by ahmetyalp** [comment]
@ivokub It probably works. Do you have an estimation for a new release date?

**Comment by ivokub** [comment]
Great it worked!

**Pull request merged**
